const translations = {
  "en": {
    "skip": "Skip to content",
    "menu": "Menu",
    "navMethod": "HOW IT WORKS",
    "navUse": "USE",
    "navContribute": "CONTRIBUTE",
    "navAbout": "ABOUT",
    "homeLabel": "zero-shelter home",
    "primaryNavigation": "Primary navigation",
    "footerNavigation": "Footer navigation",
    "languageSelector": "Language selector",
    "productProperties": "Product properties",
    "methodList": "zero-shelter method",
    "description": "Review dependency scanner findings, upgrade guidance, and baseline changes in a terminal, HTML report, CI job, or coding agent.",
    "heroOverline": "Dependency reports",
    "heroTitle": "Review dependency findings.<br><em>Choose what to do next.</em>",
    "heroSummary": "zero-shelter combines scanner reports, ranks findings, and shows available upgrade commands. Use it directly or with a coding agent.",
    "copy": "Copy",
    "factLocal": "Run locally",
    "factNode": "Node 20+",
    "factRuntime": "No runtime dependencies",
    "factDeterministic": "Same input, same result",
    "factTelemetry": "No runtime telemetry",
    "exampleCaption": "Excerpt from v0.0.10 with a saved npm report",
    "homeExplore": "From scanner reports to review.",
    "homeExploreText": "Inspect findings and available commands in the terminal or an HTML report. Use the same results in CI or a coding agent.",
    "homeMethodLink": "See how it works <span aria-hidden=\"true\">→</span>",
    "flowCollect": "Read the findings",
    "flowCollectText": "Read supported audit reports and optionally add osv-scanner results.",
    "flowReconcile": "Combine matching findings",
    "flowReconcileText": "Merge findings with matching package, ecosystem, and advisory identifiers. Keep suspected duplicates visible.",
    "flowAct": "Review the available actions",
    "flowActText": "Check upgrade guidance and compare results with decisions recorded in the baseline.",
    "startOverline": "Get started",
    "startTitle": "Browse the project.",
    "startLead": "The preview package, source, docs, and releases are public.",
    "startGithub": "GitHub",
    "startGithubText": "Source, docs, issues, and contribution.",
    "startNpm": "npm",
    "startNpmText": "Package details and releases.",
    "methodOverline": "How it works",
    "methodTitle": "How reports<br>become findings.",
    "methodPageLead": "The same rules produce the terminal, JSON, SARIF, and HTML results.",
    "stepOneTitle": "Collect",
    "stepOneText": "Run a supported audit command, add osv-scanner when available, or read saved reports with --input.",
    "stepTwoTitle": "Reconcile",
    "stepTwoText": "Merge matching package, ecosystem, and advisory identifiers. Report suspected duplicates separately.",
    "stepThreeTitle": "Judge",
    "stepThreeText": "Rank findings using documented integer weights. Show the reasons with --explain.",
    "stepFourTitle": "Act",
    "stepFourText": "Show available upgrade guidance and compare findings with the baseline. Some findings have no published fix.",
    "methodAction": "Read the method in the README <span aria-hidden=\"true\">↗</span>",
    "methodNotesOverline": "Read the result",
    "methodNotesTitle": "Understanding<br><em>the result.</em>",
    "methodNotesLead": "Check the scanner sources, outstanding findings, and available actions before changing dependencies.",
    "methodRecordTitle": "Record a risk decision",
    "methodRecordText": "Use --update-baseline only after reviewing and accepting the reported risks. The baseline supports reasons, owners, and expiry dates; the command does not decide those for you.",
    "methodContractTitle": "Exit codes for CI",
    "methodContractText": "0 means no new findings, 1 means new findings, and 2 means the tool could not judge. A baseline can contain accepted findings even when the command exits 0.",
    "methodContractCode": "0 = no new findings · 1 = new findings · 2 = could not judge",
    "methodRemediationTitle": "Upgrade guidance",
    "methodRemediationText": "Commands follow the detected package manager. Verified counts depend on supported lockfile data. Forced versions for indirect dependencies need review because they can break the parent package.",
    "methodNotesAction": "Read the stability contract <span aria-hidden=\"true\">↗</span>",
    "useOverline": "In practice",
    "useTitle": "Use the terminal,<br>CI, or a coding agent.",
    "usePageLead": "Choose the workflow that fits your project. Each uses the same dependency findings.",
    "useOneTitle": "Terminal",
    "useOneText": "Run a scan with Node 20 or later and supported package files, or read a saved report.",
    "useTwoTitle": "CI",
    "useTwoText": "Export SARIF and use the exit code to fail a job when new findings are reported.",
    "useThreeTitle": "Coding agent",
    "useThreeText": "Pass findings and available commands to a coding agent, then check its changes by running judge again.",
    "useAction": "Open installation and CI docs <span aria-hidden=\"true\">↗</span>",
    "useGuideOverline": "First run",
    "useGuideTitle": "Run a scan.<br>Review the results.",
    "useGuideLead": "Inspect the findings and available fixes. Recording a baseline is an optional risk decision, not a required installation step.",
    "useInspectTitle": "Inspect",
    "useInspectText": "Use supported project files or supply a saved report with --input. If no usable report is available, the command exits 2.",
    "useRecordTitle": "Accept risks, if needed",
    "useRecordText": "After reviewing the risks, --update-baseline records the current findings as accepted. It does not fix them. Add a reason, owner, and expiry where appropriate.",
    "useGateTitle": "Gate",
    "useGateText": "Write SARIF for GitHub Code Scanning and use the judgement result to fail on new findings.",
    "useAgentOverline": "Agent route",
    "useAgentTitle": "Work with a coding agent.",
    "useAgentText": "The hook adds findings to a supported editor's prompt context. It does not block or rewrite prompts, and exits quietly on errors. The agent's changes still need review and a new judge run.",
    "usePluginTitle": "Claude Code plugin",
    "usePluginText": "The plugin provides setup, explanation, remediation, baseline, and CI skills.",
    "useAgentAction": "Read the hook contract <span aria-hidden=\"true\">↗</span>",
    "useOutputOverline": "Output formats",
    "useOutputText": "Text is for people, JSON for tools, SARIF for GitHub, and HTML for a shareable local report. Use <code>--explain</code> for the score and <code>--record</code>, then <code>zero-shelter history</code>, to see changes over time.",
    "useOutputAction": "See all options <span aria-hidden=\"true\">↗</span>",
    "aboutOverline": "Why it exists · who maintains it",
    "aboutTitle": "About<br><em>zero-shelter.</em>",
    "aboutLead": "An open-source tool for reviewing dependency scanner findings, available as a preview package on npm.",
    "aboutReasonLabel": "Why zero-shelter",
    "aboutMaintainersLabel": "Maintainers",
    "aboutMaintainersText": "Development, bug reports, and reviews take place on GitHub. See the contribution guide to participate.",
    "contributorsLabel": "zero-shelter contributors",
    "aboutGithub": "Explore zero-shelter on GitHub <span aria-hidden=\"true\">→</span>",
    "githubProfile": "GitHub",
    "copied": "Command copied",
    "copyFailed": "Copy unavailable. Select the command and copy it manually.",
    "contributeTitle": "Contribute to<br><em>zero-shelter.</em>",
    "contributeLead": "Choose the route that fits your change.",
    "contributeRoutesTitle": "Where would you like to help?",
    "contributionRoutes": "Contribution routes",
    "contributeProductLabel": "Product",
    "contributeProductTitle": "Product and documentation",
    "contributeProductText": "Start with an Issue, then use the contribution guide.",
    "contributeProductAction": "Read the guide <span aria-hidden=\"true\">↗</span>",
    "contributeWebsiteLabel": "Website",
    "contributeWebsiteTitle": "This website",
    "contributeWebsiteText": "Suggest content, design, or accessibility improvements.",
    "contributeWebsiteAction": "Open a website Issue <span aria-hidden=\"true\">↗</span>",
    "contributeSecurityLabel": "Security",
    "contributeSecurityTitle": "Private vulnerability report",
    "contributeSecurityText": "Keep undisclosed vulnerability details out of Issues and PRs.",
    "contributeSecurityAction": "Read the policy <span aria-hidden=\"true\">↗</span>",
    "aboutReasonFirst": "Different scanners can report the same dependency vulnerability under different identifiers. Reviewing separate reports also means comparing them with risks the project has already accepted.",
    "aboutReasonSecond": "zero-shelter merges findings when their package, ecosystem, and advisory identifiers match, ranks the results, and compares them with the baseline. It keeps suspected duplicates separate.",
    "aboutEvidenceLabel": "What we have measured",
    "aboutEvidenceText": "The repository includes saved scanner reports and a reproducible comparison of merged findings and upgrade guidance. These measurements describe those captures; they do not establish ranking accuracy or prove a project is secure.",
    "aboutEvidenceAction": "Read the benchmark <span aria-hidden=\"true\">↗</span>",
    "aboutStatusLabel": "Current release",
    "aboutStatusText": "Requires Node 20 or later. The tool has no runtime dependencies, telemetry, or network requests of its own. Invoked scanners have their own network behavior. See release notes for shipped changes and the stability contract for compatibility commitments.",
    "aboutStatusAction": "Read the stability contract <span aria-hidden=\"true\">↗</span>",
    "aboutBoundaryLabel": "v1 boundary",
    "aboutBoundaryText": "The current release covers dependency findings. SAST, secret scanning, and prompt-intent analysis are not provided.",
    "aboutBoundaryAction": "Read the v1 scope <span aria-hidden=\"true\">↗</span>",
    "exampleNote": "This excerpt omits the indirect dependency warning and baseline guidance. Counts describe this saved report, not a live scan or a confirmed fix.",
    "exampleSource": "View the example input"
  },
  "ko": {
    "skip": "본문으로 건너뛰기",
    "menu": "메뉴",
    "navMethod": "작동 방식",
    "navUse": "사용하기",
    "navContribute": "기여하기",
    "navAbout": "소개",
    "homeLabel": "zero-shelter 홈",
    "primaryNavigation": "주요 탐색",
    "footerNavigation": "푸터 탐색",
    "languageSelector": "언어 선택",
    "productProperties": "제품 특성",
    "methodList": "zero-shelter 처리 방식",
    "description": "의존성 스캐너의 결과, 업그레이드 안내, baseline 변경을 터미널·HTML 보고서·CI·코딩 에이전트에서 확인합니다.",
    "heroOverline": "의존성 검사 결과",
    "heroTitle": "의존성 검사 결과를 모아<br><em>할 일을 정합니다.</em>",
    "heroSummary": "스캐너 결과를 합치고 우선순위와 가능한 업그레이드 명령을 보여줍니다. 직접 사용하거나 코딩 에이전트와 함께 사용할 수 있습니다.",
    "copy": "복사",
    "factLocal": "로컬에서 실행",
    "factNode": "Node 20 이상",
    "factRuntime": "런타임 의존성 없음",
    "factDeterministic": "같은 입력, 같은 결과",
    "factTelemetry": "실행 중 텔레메트리 없음",
    "exampleCaption": "저장된 npm 보고서를 읽은 v0.0.10 출력 일부",
    "homeExplore": "스캐너 결과를 모아서 검토합니다.",
    "homeExploreText": "터미널이나 HTML 보고서에서 검사 결과와 명령을 확인합니다. 같은 결과를 CI나 코딩 에이전트에서도 사용할 수 있습니다.",
    "homeMethodLink": "작동 방식 보기 <span aria-hidden=\"true\">→</span>",
    "flowCollect": "결과를 읽습니다",
    "flowCollectText": "지원하는 감사 보고서를 읽고, 필요하면 osv-scanner 결과를 추가합니다.",
    "flowReconcile": "일치하는 결과를 합칩니다",
    "flowReconcileText": "패키지·생태계·취약점 식별자가 일치하는 결과를 합칩니다. 중복으로 의심되는 항목은 따로 표시합니다.",
    "flowAct": "가능한 조치를 검토합니다",
    "flowActText": "업그레이드 안내를 확인하고 baseline에 기록한 결정과 현재 결과를 비교합니다.",
    "startOverline": "시작하기",
    "startTitle": "프로젝트를 살펴보세요.",
    "startLead": "프리뷰 패키지, 소스 코드, 문서와 릴리스를 공개합니다.",
    "startGithub": "GitHub",
    "startGithubText": "소스 코드, 문서, 이슈와 기여 방법.",
    "startNpm": "npm",
    "startNpmText": "패키지 정보와 릴리스 내역.",
    "methodOverline": "작동 방식",
    "methodTitle": "보고서를 읽고<br>검토할 항목을 정합니다.",
    "methodPageLead": "터미널·JSON·SARIF·HTML 출력에 같은 판정 규칙을 적용합니다.",
    "stepOneTitle": "수집",
    "stepOneText": "지원하는 감사 명령과 설치된 osv-scanner를 실행하거나 --input으로 저장된 보고서를 읽습니다.",
    "stepTwoTitle": "정리",
    "stepTwoText": "패키지·생태계·취약점 식별자가 일치하는 결과를 합칩니다. 중복으로 의심되는 항목은 따로 표시합니다.",
    "stepThreeTitle": "판단",
    "stepThreeText": "문서에 명시된 정수 가중치로 순위를 계산합니다. --explain으로 계산 이유를 확인할 수 있습니다.",
    "stepFourTitle": "조치",
    "stepFourText": "가능한 업그레이드를 안내하고 baseline과 비교합니다. 수정 버전이 없는 항목도 있습니다.",
    "methodAction": "README에서 작동 방식 보기 <span aria-hidden=\"true\">↗</span>",
    "methodNotesOverline": "결과 읽기",
    "methodNotesTitle": "결과를<br><em>읽는 방법.</em>",
    "methodNotesLead": "의존성을 변경하기 전에 검사에 참여한 스캐너, 검토할 항목, 가능한 조치를 확인합니다.",
    "methodRecordTitle": "위험 수용 결정 기록",
    "methodRecordText": "보고된 위험을 검토하고 수용하기로 결정한 경우에만 --update-baseline을 사용합니다. baseline에는 사유·담당자·만료일을 기록할 수 있으며, 명령이 이를 대신 결정하지는 않습니다.",
    "methodContractTitle": "CI에서 사용하는 종료 코드",
    "methodContractText": "0은 새 항목 없음, 1은 새 항목 있음, 2는 판정 불가입니다. 종료 코드가 0이어도 baseline에 수용한 항목이 남아 있을 수 있습니다.",
    "methodContractCode": "0 = 새 항목 없음 · 1 = 새 항목 있음 · 2 = 판정 불가",
    "methodRemediationTitle": "업그레이드 안내",
    "methodRemediationText": "명령은 감지한 패키지 관리자에 맞춥니다. 조치 건수는 지원하는 lockfile 정보로 확인한 경우에 표시합니다. 간접 의존성의 버전을 강제하면 상위 패키지가 깨질 수 있어 검토가 필요합니다.",
    "methodNotesAction": "안정성 계약 보기 <span aria-hidden=\"true\">↗</span>",
    "useOverline": "사용 방법",
    "useTitle": "터미널·CI·코딩 에이전트에서<br>사용합니다.",
    "usePageLead": "프로젝트에 맞는 방법을 선택합니다. 어느 방법이든 같은 의존성 검사 결과를 사용합니다.",
    "useOneTitle": "터미널",
    "useOneText": "Node 20 이상과 지원하는 패키지 파일로 검사하거나 저장된 보고서를 읽습니다.",
    "useTwoTitle": "CI",
    "useTwoText": "SARIF를 내보내고, 새 항목이 보고되면 종료 코드에 따라 CI 작업을 실패시킵니다.",
    "useThreeTitle": "코딩 에이전트",
    "useThreeText": "검사 결과와 가능한 명령을 코딩 에이전트에 전달합니다. 변경 후 judge를 다시 실행해 결과를 확인합니다.",
    "useAction": "설치와 CI 문서 보기 <span aria-hidden=\"true\">↗</span>",
    "useGuideOverline": "첫 실행",
    "useGuideTitle": "검사를 실행하고<br>결과를 확인합니다.",
    "useGuideLead": "검사 결과와 가능한 수정 방법을 살펴봅니다. baseline 기록은 설치에 필요한 단계가 아니라 위험을 수용할 때 선택하는 작업입니다.",
    "useInspectTitle": "확인",
    "useInspectText": "지원하는 프로젝트 파일을 사용하거나 --input으로 저장된 보고서를 지정합니다. 사용할 수 있는 보고서가 없으면 종료 코드는 2입니다.",
    "useRecordTitle": "필요한 경우 위험 수용",
    "useRecordText": "위험을 검토한 후 --update-baseline으로 현재 항목을 수용했다고 기록합니다. 취약점을 고치는 명령은 아닙니다. 필요에 따라 사유·담당자·만료일을 추가합니다.",
    "useGateTitle": "CI 연결",
    "useGateText": "GitHub Code Scanning용 SARIF를 만들고, 새 항목이 생기면 판정 결과로 작업을 실패시킵니다.",
    "useAgentOverline": "코딩 에이전트 연동",
    "useAgentTitle": "코딩 에이전트와<br>함께 사용합니다.",
    "useAgentText": "hook은 지원하는 편집기의 프롬프트에 검사 결과를 추가합니다. 프롬프트를 차단하거나 바꾸지 않고 오류가 나면 출력 없이 종료합니다. 에이전트가 수정한 내용도 검토하고 judge를 다시 실행해야 합니다.",
    "usePluginTitle": "Claude Code 플러그인",
    "usePluginText": "설정, 결과 설명, 수정, baseline, CI를 위한 스킬을 제공합니다.",
    "useAgentAction": "hook 계약 보기 <span aria-hidden=\"true\">↗</span>",
    "useOutputOverline": "출력 형식",
    "useOutputText": "터미널에서 읽는 text, 도구가 읽는 JSON, GitHub용 SARIF, 공유 가능한 로컬 HTML 보고서를 제공합니다. 점수 계산은 <code>--explain</code>으로 확인합니다. <code>--record</code>로 기록한 실행은 <code>zero-shelter history</code>에서 비교할 수 있습니다.",
    "useOutputAction": "전체 옵션 보기 <span aria-hidden=\"true\">↗</span>",
    "aboutOverline": "프로젝트 소개",
    "aboutTitle": "zero-shelter<br><em>소개.</em>",
    "aboutLead": "의존성 스캐너의 결과를 검토하는 오픈소스 도구입니다. npm에서 프리뷰 패키지를 제공합니다.",
    "aboutReasonLabel": "zero-shelter를 만든 이유",
    "aboutMaintainersLabel": "유지보수 담당자",
    "aboutMaintainersText": "GitHub에서 개발, 버그 보고와 리뷰를 진행합니다. 참여 방법은 기여 안내를 확인해 주세요.",
    "contributorsLabel": "zero-shelter 기여자",
    "aboutGithub": "GitHub에서 zero-shelter 살펴보기 <span aria-hidden=\"true\">→</span>",
    "githubProfile": "GitHub 프로필",
    "copied": "명령을 복사했습니다",
    "copyFailed": "복사하지 못했습니다. 명령을 선택해 직접 복사해 주세요.",
    "contributeTitle": "zero-shelter에<br><em>기여하기.</em>",
    "contributeLead": "변경에 맞는 경로를 고르세요.",
    "contributeRoutesTitle": "어디에 기여할까요?",
    "contributionRoutes": "기여 경로",
    "contributeProductLabel": "제품",
    "contributeProductTitle": "제품과 문서",
    "contributeProductText": "이슈에서 시작하고, 제품 기여 가이드를 따르세요.",
    "contributeProductAction": "가이드 읽기 <span aria-hidden=\"true\">↗</span>",
    "contributeWebsiteLabel": "웹사이트",
    "contributeWebsiteTitle": "웹사이트",
    "contributeWebsiteText": "내용, 디자인, 접근성 개선을 제안하세요.",
    "contributeWebsiteAction": "웹사이트 이슈 열기 <span aria-hidden=\"true\">↗</span>",
    "contributeSecurityLabel": "보안",
    "contributeSecurityTitle": "취약점은 비공개 제보",
    "contributeSecurityText": "아직 공개되지 않은 취약점의 상세 내용은 공개 이슈와 PR에 작성하지 않습니다.",
    "contributeSecurityAction": "정책 읽기 <span aria-hidden=\"true\">↗</span>",
    "aboutReasonFirst": "서로 다른 스캐너가 같은 의존성 취약점을 다른 식별자로 보고할 수 있습니다. 각 보고서를 검토할 때는 프로젝트가 이미 수용한 위험과도 비교해야 합니다.",
    "aboutReasonSecond": "패키지·생태계·취약점 식별자가 일치하는 결과를 합친 뒤 순위를 계산하고 baseline과 비교합니다. 중복으로 의심되는 항목은 따로 표시합니다.",
    "aboutEvidenceLabel": "측정한 것과 한계",
    "aboutEvidenceText": "저장소에는 스캐너 보고서와 병합 결과·업그레이드 안내를 재현하는 비교 자료가 있습니다. 해당 자료에서 측정한 결과이며, 순위의 정확도나 프로젝트의 안전성을 입증하지는 않습니다.",
    "aboutEvidenceAction": "벤치마크 보기 <span aria-hidden=\"true\">↗</span>",
    "aboutStatusLabel": "현재 배포 버전",
    "aboutStatusText": "Node 20 이상이 필요합니다. 런타임 의존성, 텔레메트리, 도구 자체의 네트워크 요청은 없습니다. 실행하는 스캐너는 각자의 네트워크 동작을 따릅니다. 배포된 변경은 릴리스 설명에서, 호환성 기준은 안정성 문서에서 확인할 수 있습니다.",
    "aboutStatusAction": "안정성 계약 보기 <span aria-hidden=\"true\">↗</span>",
    "aboutBoundaryLabel": "v1 범위",
    "aboutBoundaryText": "현재 배포 버전은 의존성 검사 결과를 다룹니다. SAST, 비밀 정보 검사, 프롬프트 의도 분석은 제공하지 않습니다.",
    "aboutBoundaryAction": "v1 범위 보기 <span aria-hidden=\"true\">↗</span>",
    "exampleNote": "간접 의존성 경고와 baseline 안내를 생략한 예시입니다. 건수는 저장된 보고서 기준이며, 실시간 검사나 수정 완료를 뜻하지 않습니다.",
    "exampleSource": "예시 입력 보기"
  }
};

const feedback = document.querySelector('.copy-feedback');
const description = document.querySelector('#page-description');
let activeLanguage = window.localStorage.getItem('zero-shelter-language') || (navigator.language.startsWith('ko') ? 'ko' : 'en');

function applyLanguage(language) {
  activeLanguage = language;
  document.documentElement.lang = language;
  document.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = translations[language][element.dataset.i18n]; });
  document.querySelectorAll('[data-i18n-html]').forEach((element) => { element.innerHTML = translations[language][element.dataset.i18nHtml]; });
  document.querySelectorAll('[data-i18n-aria]').forEach((element) => { element.setAttribute('aria-label', translations[language][element.dataset.i18nAria]); });
  document.querySelectorAll('[data-language]').forEach((button) => { button.setAttribute('aria-pressed', String(button.dataset.language === language)); });
  description.setAttribute('content', translations[language].description);
  document.title = language === 'ko' ? 'zero-shelter: 의존성 검사 결과 검토' : 'zero-shelter: review dependency findings';
  window.localStorage.setItem('zero-shelter-language', language);
}

document.querySelectorAll('[data-language]').forEach((button) => button.addEventListener('click', () => applyLanguage(button.dataset.language)));
const menuButton = document.querySelector('.menu-button');
const siteNavigation = document.querySelector('#site-nav');

function setMenu(open) {
  if (!menuButton || !siteNavigation) return;
  menuButton.setAttribute('aria-expanded', String(open));
  siteNavigation.classList.toggle('is-open', open);
}

menuButton?.addEventListener('click', () => setMenu(menuButton.getAttribute('aria-expanded') !== 'true'));
siteNavigation?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => setMenu(false)));
document.addEventListener('keydown', (event) => {
  if (event.key === 'Escape') setMenu(false);
});
document.querySelectorAll('[data-copy]').forEach((button) => button.addEventListener('click', async () => {
  let copied = false;
  try {
    await navigator.clipboard.writeText(button.dataset.copy);
    copied = true;
  } catch {
    const input = document.createElement('textarea');
    input.value = button.dataset.copy;
    document.body.append(input);
    input.select();
    try { copied = document.execCommand('copy'); } catch { copied = false; }
    input.remove();
  }
  feedback.textContent = translations[activeLanguage][copied ? 'copied' : 'copyFailed'];
  feedback.classList.add('visible');
  window.setTimeout(() => feedback.classList.remove('visible'), 1800);
}));

applyLanguage(activeLanguage);
